routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

Auth::routes();

Route::group([
    'middleware' => ['web', 'cookie_order'],
], function () {

    Route::get('/', 'Client\CategoriesController@read');
//Route::get('/', 'Client\ProductsController@getProducts');


    Route::get('/home', 'HomeController@index')->name('home');


    Route::get('news-more/{id}', 'Client\NewsCommentsController@newsComments');

    Route::post('add-news-comment', 'Client\NewsCommentsController@addComment');

    Route::get('news-comment/delete/{id}', 'Client\NewsCommentsController@remove');

    /**
    *Client NewsController
    */

    Route::get('news', 'Client\NewsController@getNewsPage');
    
    Route::get('category/{id}', 'Client\ProductsController@getProducts');

    Route::post('filter', 'Client\FilterController@getFilter')->name('filter');

    Route::get('product/show/{id}', 'Client\DescriptionsController@getDescription');

    Route::post('product/show/add/comment', 'Client\CommentsController@create');

    Route::post('/add/newsletter/', 'Client\NewslettersController@addEmail');

    Route::post('/send', 'Client\FeedbacksController@feedback' );

    Route::post('product-mark', 'Client\MarksController@setMark');

    Route::get('authentication', 'AuthController@auth');

    Route::get('/search', 'Client\CategoriesController@search');

    Route::get('/comment/delete/{id}', 'Client\CommentsController@remove');

    Route::get('/faqs', 'Client\FaqsController@faqs');

    Route::get('/about', 'Client\AboutController@about');

    Route::get('/delivery', 'Client\DeliveryController@delivery');

    Route::get('/pay', 'Client\PayController@pay');

    Route::get('/contact', 'Client\ContactController@contact');

    Route::get('/discount', 'Client\DiscountController@discount');

    Route::get('/feature', 'Client\FeatureController@feature');

    Route::get('/bestsellers', 'Client\BestsellerController@bestsellers');

    Route::get('/send', 'Client\MailController@send');
    Route::get('time', function () {
        var_dump(session_get_cookie_params());
        exit;
    });

    //OrderController
    Route::post('order/cart-add-product', 'Client\OrderController@cartAddProduct')->name('cart.add.product');
    Route::get('remove/cart-order/{order_id}', 'Client\OrderController@removeCartOrder')->name('remove.cart.order');
    Route::get('page-cart', 'Client\OrderController@getPageCart')->name('get.page.cart');
    Route::get('order-product/plus/{product_id}', 'Client\OrderController@plusProductCart')->name('plus.product.cart');
    Route::get('order-product/minus/{product_id}', 'Client\OrderController@minusProductCart')->name('minus.product.cart');
    Route::get('order-product/remove-all/{product_id}', 'Client\OrderController@removeAllProductCart')->name('remove.product.cart');
    Route::get('order/billing-page', 'Client\OrderController@billingPage')->name('order.billing.page');
    Route::post('add-request-order', 'Client\OrderController@billingAddOrder')->name('add.request.order');

    Route::post('success', 'Client\OrderController@sucessorder');
    Route::post('fail', 'Client\OrderController@falseorder');
    Route::get('result', 'Client\OrderController@result');

});

    /*
     * Ajax templates
     */

    Route::get('get_template/{id}', 'Admin\TemplateDetailsController@ajaxTemplates');

    /*
     * Ajax SubCategories
     */
    Route::get('get_sub_categories/{id}', 'Admin\AdminSubCategoriesController@ajaxSubCategories');


Route::group([
    'prefix' => config('app.admin_prefix'),
    'middleware' => ['auth', 'level:2']
], function () {
    Route::get('admin', 'Admin\AdminCategoriesController@getcategories');
    Route::get('admin_categories', 'Admin\AdminCategoriesController@getcategories');
    Route::get('add_categories', 'Admin\AdminCategoriesController@add');
    Route::get('add_some_products', 'Admin\AdminProductsController@addSome');

    Route::post('/add_categories/save', 'Admin\AdminCategoriesController@create');
    Route::post('/add_some_products/save', 'Admin\AdminProductsController@createSome');

    Route::get('admincategories_update/{id}', 'Admin\AdminCategoriesController@getUpdate');
    Route::post('/update_categories/save', 'Admin\AdminCategoriesController@cat_update');
    Route::get('/admincategories/delete/{id}', 'Admin\AdminCategoriesController@remove');
    Route::get('admin_sub_categories', 'Admin\AdminSubCategoriesController@getsubcategories');
    Route::get('/adminsubcategories/update/{id}', 'Admin\AdminSubCategoriesController@getUpdate');
    Route::get('add_sub_categories', 'Admin\AdminSubCategoriesController@add');
    Route::post('/add_sub_categories/save', 'Admin\AdminSubCategoriesController@create');
    Route::get('/adminsubcategories/delete/{id}', 'Admin\AdminSubCategoriesController@remove');
    Route::post('/update_sub_categories/save', 'Admin\AdminSubCategoriesController@sub_cat_update');
    Route::get('admin_products', 'Admin\AdminProductsController@getProducts');
    Route::get('/adminproducts/delete/{id}', 'Admin\AdminProductsController@remove');
    Route::get('/adminproducts/update/{id}', 'Admin\AdminProductsController@getUpdate');
    Route::get('add_products', 'Admin\AdminProductsController@add');
    Route::get('/categories/change/{id}' , 'Admin\AdminProductsController@changeSubCategories');
    Route::post('/add_products/save', 'Admin\AdminProductsController@create');
    Route::post('/update_products/save', 'Admin\AdminProductsController@products_update');
    Route::get('admin_descriptions', 'Admin\AdminDescriptionsController@getDescriptions');
    Route::get('/admindescriptions/update/{id}', 'Admin\AdminDescriptionsController@getUpdate');
    Route::post('/update_descriptions/save', 'Admin\AdminDescriptionsController@descriptions_update');
    Route::get('/admindescriptions/delete/{id}', 'Admin\AdminDescriptionsController@remove');
    Route::get('/img/delete/{id}', 'Admin\AdminProductsController@img_delete');
    Route::post('add-details', 'Admin\AdminDetailsController@addDetails');
    Route::post('/update_detail/save', 'Admin\AdminDetailsController@detail_update');

    Route::get('product-details/{id}', 'Admin\AdminDetailsController@getDetails');
    Route::get('admin_details', 'Admin\AdminDetailsController@getDetails');
    Route::get('/product-details/update/{id}', 'Admin\AdminDetailsController@getUpdate');
    Route::get('/product-details/delete/{id}', 'Admin\AdminDetailsController@remove');
    Route::get('/banners', 'Admin\BannersController@get_banners');
    Route::get('/add_banners', 'Admin\BannersController@add_banners');
    Route::post('/add_banners/save', 'Admin\BannersController@create');
    Route::get('/banners/delete/{id}', 'Admin\BannersController@remove');
    Route::get('/brands', 'Admin\BrandsController@get_brands');
    Route::get('/add_brands', 'Admin\BrandsController@add_brands');
    Route::post('/add_brands/save', 'Admin\BrandsController@create');
    Route::get('/brands/delete/{id}', 'Admin\BrandsController@remove');
    Route::get('/feedbacks', 'Admin\AdminFeedbacksController@feedbacks');

    /**
     * AdminNewslettersController
     */
    Route::get('/feedbacks/delete/{id}', 'Admin\AdminFeedbacksController@remove');
    Route::get('/feedback/change_status/{id}/{status}', 'Admin\AdminFeedbacksController@changeStatus');
    Route::get('/newsletters', 'Admin\AdminNewslettersController@newsletters');
    Route::get('/newsletters/delete/{id}', 'Admin\AdminNewslettersController@remove');

    /**
     *Admin OrderRequestController
     */
    Route::get('/orders', ['uses' => 'Admin\AdminOrderRequestsController@get_orders', 'as'=>'order.requested.list']);
    Route::get('/info/order/{id}', 'Admin\AdminOrdersController@get_orders');
    Route::get('/orders/delete/{id}', 'Admin\AdminOrderRequestsController@remove');

    /**
     * AdminOrdersController
     */


    /**
     * ImageController
     */
    Route::get('/product_images/{id}', 'Admin\ImagesController@get_images');
    Route::post('/add_product_images', 'Admin\ImagesController@add_product_images');
    Route::get('/product_images/delete/{id}', 'Admin\ImagesController@remove');


    /**
     * ReportsController
     */
    Route::get('/reports', 'Admin\ReportsController@reports');
    Route::get('reports/download', 'Admin\ReportsController@download');

    Route::get('/orders/change_status/{id}/{status}', 'Admin\AdminOrderRequestsController@changeStatus');

    /*Template Detailes Route */
    Route::resource('template_details', 'Admin\TemplateDetailsController', [
        'names' => [
            'as' => config('app.admin_prefix')
        ]
    ]);
    /*Template Detailes Items Route */
    Route::resource('template_details_items', 'Admin\TemplateDetailsItemsController',[
        'names' => [
            'as' => config('app.admin_prefix')
        ]
    ]);
    /*get templates details*/
    Route::get('/get_templates/{id}/{product_id}', [
        'uses' =>'Admin\GetTemplatesController@getTemplate',
        'as'   =>'template.get'
    ]);
    Route::post('/save_template_details', [
        'uses' =>'Admin\GetTemplatesController@saveTemplate',
        'as'   =>'template.save'
    ]);


    Route::get('report-lists', 'Admin\ReportsController@lists');

    /**
     *Admin NewsController
     */

    Route::get('news', 'Admin\AdminNewsController@getNewsPage');
    Route::get('add_news', 'Admin\AdminNewsController@addNews');
    Route::post('add_news/save', 'Admin\AdminNewsController@create');
    Route::get('news/update/{id}', 'Admin\AdminNewsController@getUpdateNews');

resources/views/admin/partials/add_brands.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
    @if(\Session::has('message'))
        <div class="alert alert-success" role="alert">
            <p> <i class="fa fa-check-circle-o"> </i> {{Session::get('message')}} </p>
        </div>
    @endif
    
    <div class="col-3">
        <form action="{{url(config('app.admin_prefix').'/add_brands/save')}}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="container">
            <label for="exampleInputEmail1">Название<span class="text-danger">*</span></label>
            <input type="text" name="name" class="form-control mt-1" id="name" placeholder="Название" required>
            
            <label for="exampleInputEmail1" class="mt-2">Загрузить картинку<span class="text-danger">*</span></label><br/>
            <span class="text-danger small"><i>файл должен быть формата jpg, jpeg, png и с разрешением больше 144x35</i></span>
            <input  type="file" name="img" class="mt-1" id="img" required/>
            
            <input type="submit" class="btn btn-success mt-3" value="Добавить">    
        @if (count($errors)) 
        <div class="form-group">
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                    @endforeach    
                </ul>
            </div>
        </div>
        @endif
        </div>    
        </form>        
    </div>
</main>

@endsection

resources/views/admin/partials/add_sub_categories.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
    @if(\Session::has('message'))
        <div class="alert alert-success" role="alert">
            <p> <i class="fa fa-check-circle-o"> </i> {{Session::get('message')}} </p>
        </div>
    @endif
    <div class="col-3">
        <form action="/cpanel/add_sub_categories/save" method="post">
            {{ csrf_field() }}
            <div class="container">
                <label for="exampleInputEmail1">Название Подкатегории</label>
                <input type="text" name="name" class="form-control mt-1" id="name" placeholder="Название Подкатегории"/>
                <label for="exampleInputEmail1" class="mt-2">Название Категории</label>
                
                <select name="category" onchange="getSelect();" class="form-control mt-1" id="category">    
                    @foreach($categories as $cat)
                    <option value="{{ $cat->id }}"> {{ $cat->name }} </option>
                    @endforeach

                </select>
                <input type="submit" class="btn btn-success mt-3" value="Добавить" />    
            @if (count($errors)) 
            <div class="form-group">
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{$error}}</li>
                        @endforeach    
                    </ul>
                </div>
            </div>
            @endif
            </div>    
        </form>        
    </div>
</main>
<script>
function getSelect() {
    var select = document.getElementById('category').value;
    console.log(select);
}
</script>
@endsection

resources/views/admin/partials/descriptions.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
<div class="container-fluid">
    <div class="card mb-4 wow fadeIn">
        <div class="card-body d-sm-flex justify-content-between">
            <h4 class="mb-2 mb-sm-0 pt-1">
                Описание товаров
            </h4>    
            
        </div>
        <div class="container">
        <table class="table table-striped table-bordered data-table">
            
            <thead>
            <tr>
                <th scope="col"><strong>№</strong></th>     
                <th scope="col-md-4"><strong>Товар</strong></th>
                <th scope="col" style="width:25%"><strong>Описание</strong></th>
                <th scope="col"><strong>Действие</strong></th>
                <th scope="col"><strong>Создан</strong></th>
                <th scope="col"><strong>Обновлен</strong></th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
            @foreach($product->descriptions as $desc)
            <tr>
                <th scope="row">{{$product->id}}</th>
                <td>{{$product->name}}</td>
                <td>{{$desc->name}}</td>
                <td>
                    <a class="btn btn-info btn-sm text-white"
                        href="admindescriptions/update/{{$product->id}}">
                    <i class="fa fa-edit"></i> Описание</a>
                    <a class="btn btn-danger btn-sm text-white"
                        href="admindescriptions/delete/{{$desc->id}}">
                    <i class="fa fa-trash-o"></i> Удалить</a>
                </td>
                <td>{{$desc->created_at}}</td>
                <td>{{$desc->updated_at}}</td>
                {{-- <td>
                <a class="btn btn-warning btn-sm text-white"
                    href="admincategories_update/{{$desc->id}}"
                >
                <i class="fa fa-edit"></i> Изменить</a>
                <a class="btn btn-danger btn-sm text-white" 
                    href="/admincategories/delete/{{$desc->id}}">
                <i class="fa fa-trash-o"></i> Удалить</a>
                </td> --}}
            </tr>
            @endforeach
            @endforeach
            </tbody>
        </table>
        {{--{{$products->links()}}--}}
        </div>
    </div>
</div>
</main>
<script src="{{ asset('teleglobal\callcenter\bower_components\datatables.net\js\jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('teleglobal\callcenter\bower_components\datatables.net-bs\js\dataTables.bootstrap.min.js') }}"></script>
<script>
    $(function () {
        $('.data-table').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': true
        });
    });

</script>
@endsection

resources/views/admin/partials/get_templates.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
        <div class="col-12">
        @if( Session::has('message'))
            <div class="alert alert-success" role="alert">
                <p style="font-size:2rem;">{{$success_message=Session::get('message')}}</p>
            </div>
        @endif
        <h4 class="mb-3">Товар {{App\Products::find($product_id)->name}}</h4>
        <form method="post" action="{{route('template.save')}}">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>KEY</th>
                    <th>VALUE</th>
                </tr>
                </thead>
                {{ csrf_field() }}
                <tbody>
                    @foreach($data as $row)
                        <tr>
                            <td><input name="key[]" type="hidden" value="{{$row->key}}">{{$row->key}}</td>
                            <td><input name="value[]" type="text" value="{{$row->value}}" required></td>
                        </tr>
                    @endforeach
                <tbody>
                <input type="hidden" name="product_id" value="{{$product_id}}">
            </table>
            <input type="submit" class="btn btn-success mt-3 mb-2" value="Сохранить">
            </form>
        </div>
    </main>
@endsection

resources/views/admin/partials/show_template_details.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
<div class="container-fluid">
    @if( Session::has('message'))
        <div class="alert alert-success" role="alert">
            <p>{{$success_message=Session::get('message')}}</p>
        </div>
    @endif
    <div class="card mb-4 wow fadeIn">
        <div class="card-body d-sm-flex justify-content-between">
            <h4 class="mb-2 mb-sm-0 pt-1">
                Template {{App\Template_details::where('id', '=', $id_row )->first()->name}}
            </h4>
            <form class="d-flex justify-content-center">
                <div class="col-auto  mr-auto">
                    <a href="{{route('template_details_items.show',$id_row)}} " class="btn btn-success">
                    <i class="fa fa-plus"></i>    Добавить детали
                    </a>
                </div>
            </form>
        </div>
        <div class="container">
        <table class="table table-striped table-bordered data-table">
            
            <thead>
            <tr>
                <th scope="col"><strong>№</strong></th>   
                <th scope="col-md-4"><strong>Key</strong></th>
                <th scope="col-md-4"><strong>Value</strong></th>
                <th scope="col"><strong>actions</strong></th>
                <th scope="col"><strong>created at</strong></th>
                <th scope="col"><strong>updated at</strong></th>
            </tr>
            </thead>
            <tbody>
            @foreach($data as $row)
            <tr>
                <th scope="row">{{$row->id}}</th>
                <td>{{$row->key}}</td>
                <td>{{$row->value}}</td>
                <td>
                <form action="{{ route('template_details_items.destroy',$row->id) }}" method="POST">
                    <a class="btn btn-warning btn-sm text-white"
                        href="{{route('template_details_items.edit',$row->id)}}"
                    >
                    <i class="fa fa-edit"></i> Change</a>
                
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm text-white">
                    <i class="fa fa-trash-o"></i> Delete</button>
                </form>
                </td>
                <td>{{$row->created_at}}</td>
                <td>{{$row->updated_at}}</td>
            </tr>
            @endforeach
            </tbody>
            
        </table>
        </div>
    </div>              
</div>      
</main>
<script src="{{ asset('teleglobal\callcenter\bower_components\datatables.net\js\jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('teleglobal\callcenter\bower_components\datatables.net-bs\js\dataTables.bootstrap.min.js') }}"></script>
<script>
    $(function () {
        $('.data-table').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': true
        });
    });

</script>
@endsection

resources/views/admin/partials/sidebar.blade.php
<div class="o-page__sidebar js-page-sidebar">
    <div class="c-sidebar">
        <a class="c-sidebar__brand" href="#">
                Администратор
        </a>
        
        <h4 class="c-sidebar__title">Панель Управление</h4>
        <ul class="c-sidebar__list">
            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/admin_categories')) ? 'is-active' : '' }}
                {{ (request()->is(config('app.admin_prefix').'/add_categories')) ? 'is-active' : '' }}
                {{ (request()->is(config('app.admin_prefix').'/admincategories_update/')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/admin_categories')}}">
                    <i class="fa fa-bars u-mr-xsmall"></i>Категории 
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/admin_sub_categories')) ? 'is-active' : '' }}
                {{ (request()->is(config('app.admin_prefix').'/add_sub_categories')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/admin_sub_categories')}}">
                    <i class="fa fa-align-center u-mr-xsmall"></i>Подкатегории
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/admin_products')) ? 'is-active' : '' }}
                {{ (request()->is(config('app.admin_prefix').'/add_products')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/admin_products')}}">
                    <i class="fa fa-bars u-mr-xsmall"></i>Товары
                </a>
            </li>

            
            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/admin_descriptions')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/admin_descriptions')}}">
                    <i class="fa fa-info u-mr-xsmall"></i>Описание товара
                </a>
            </li>

           <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/template_details')) ? 'is-active' : '' }}"
                    href="{{route('template_details.index')}} ">
                    <i class="fa fa-align-center u-mr-xsmall"></i>Шаблони деталей
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/news')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/news')}} ">
                    <i class="fa fa-picture-o u-mr-xsmall"></i>Новости
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/banners')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/banners')}} ">
                    <i class="fa fa-picture-o u-mr-xsmall"></i>Банеры
                </a>
            </li>
            
            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/brands')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/brands')}} ">
                    <i class="fa fa-file-image-o u-mr-xsmall"></i>Топ бренды
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/feedbacks')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/feedbacks')}} ">
                    <i class="fa fa-reply u-mr-xsmall"></i>Обратная связь
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/newsletters')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/newsletters')}} ">
                    <i class="fa fa-rss u-mr-xsmall"></i>Рассылки
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/orders')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/orders')}}">
                    <i class="fa fa-shopping-cart u-mr-xsmall"></i>Заказы
                </a>
            </li>

            <li class="c-sidebar__item">
                <a class="c-sidebar__link act {{ (request()->is(config('app.admin_prefix').'/reports')) ? 'is-active' : '' }}"
                    href="{{url(config('app.admin_prefix').'/reports')}}">
                    <i class="fa fa-database u-mr-xsmall"></i>Отчеты
                </a>
            </li>

            
        </ul>

    </div><!-- // .c-sidebar -->
</div><!-- // .o-page__sidebar -->

resources/views/admin/partials/template_details_index.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
<div class="container-fluid">
    @if( Session::has('message'))
        <div class="alert alert-success" role="alert">
            <p>{{$success_message=Session::get('message')}}</p>
        </div>
    @endif
    <div class="card mb-4 wow fadeIn">
        <div class="card-body d-sm-flex justify-content-between">
            <h4 class="mb-2 mb-sm-0 pt-1">
                Template Details
            </h4>    
        
            <form class="d-flex justify-content-center">
                <div class="col-auto  mr-auto">
                    <a href="{{route('template_details.create')}} " class="btn btn-success">
                    <i class="fa fa-plus"></i>    Добавить шаблон
                    </a>
                </div>
                <div class="col-auto  mr-auto">
                    <a href="{{route('template_details_items.create')}} " class="btn btn-success">
                    <i class="fa fa-plus"></i>    Добавить детали для шаблона
                    </a>
                </div>
            </form>
        </div>
        <div class="container">
        <table class="table table-striped table-bordered data-table">
            
            <thead>
            <tr>
                <th scope="col"><strong>№</strong></th>     
                <th scope="col-md-4"><strong>Templates</strong></th>
                <th scope="col"><strong>actions</strong></th>
                <th scope="col"><strong>created at</strong></th>
                <th scope="col"><strong>updated at</strong></th>
            </tr>
            </thead>
            <tbody>
            @foreach($data as $row)
            <tr>
                <th scope="row">{{$row->id}}</th>
                <td><a href="{{route('template_details.show',$row->id)}}">{{$row->name}}</a>
            </td>
                <td>
                <form action="{{ route('template_details.destroy',$row->id) }}" method="POST">
                    <a class="btn btn-warning btn-sm text-white"
                        href="{{route('template_details.edit',$row->id)}}"
                    >
                    <i class="fa fa-edit"></i> Change</a>
                
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm text-white">
                    <i class="fa fa-trash-o"></i> Delete</button>
                </form>
                </td>
                <td>{{$row->created_at}}</td>
                <td>{{$row->updated_at}}</td>
            </tr>
            @endforeach
            </tbody>
            
        </table>
        </div>
    </div>              
</div>      
</main>
<script src="{{ asset('teleglobal\callcenter\bower_components\datatables.net\js\jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('teleglobal\callcenter\bower_components\datatables.net-bs\js\dataTables.bootstrap.min.js') }}"></script>
<script>
    $(function () {
        $('.data-table').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': true
        });
    });

</script>
@endsection

resources/views/admin/partials/update_template_details.blade.php
@extends('admin.partials.layout')
@section('content')
<main class="o-page__content">
    @if( Session::has('message'))
        <div class="alert alert-success" role="alert">
            <p style="font-size:2rem;">{{$success_message=Session::get('message')}}</p>
        </div>
    @endif
    <div class="col-3">
        <form action="{{route('template_details.update',$data->id)}}" method="post">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}
        <div class="container">
            <label for="name">Название шаблона детали</label>
            <input type="text" name="name" class="form-control mt-1" id="name" value="{{$data->name}}">
            <input type="hidden" name="id" value="{{$data->id}}">
            <input type="submit" class="btn btn-success mt-3" value="Изменить">    
        @if (count($errors)) 
        <div class="form-group">
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                    @endforeach    
                </ul>
            </div>
        </div>
        @endif
        </div>  
        </form>      
    </div>
</main>

@endsection